- name: Configure Web Server
  hosts: aws_ec2
  become: true
  vars:
    http_port: 8080
  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: present
    - name: Configure Apache to use port 8080
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'Listen 80'
        replace: 'Listen {{ http_port }}'
    - name: Create custom index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Zantac POC</title>
          </head>
          <body>
            <h1>Welcome to Zantac Web Application</h1>
            <p>Deployed via Terraform and Ansible</p>
          </body>
          </html>
        dest: /var/www/html/index.html
    - name: Start and enable Apache
      systemd:
        name: httpd
        state: started
        enabled: true
